"""
Normalizes the raw per-system variant tables (data/variants_raw.json, one schema
per blood group system) into a single flat list of variant records with a
consistent field set (data/variants.json), which is what the website reads.

Why this exists: the eight source tables (ABO, RHD, RHCE, Duffy, Kell, Kidd,
MNS, KellOther) were compiled at different times and use slightly different
column names for the same concept (e.g. "hgvs_notation" vs "hgvs_notation_c",
"resulting_abo_phenotype" vs "resulting_phenotype"). This script maps every
system's columns onto one shared schema so the site's search/filter/sort code
only has to know one set of field names.

Run with: python3 normalize_data.py
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
RAW_PATH = ROOT / "data" / "variants_raw.json"
OUT_PATH = ROOT / "data" / "variants.json"
JS_OUT_PATH = ROOT / "assets" / "data.js"
CSV_OUT_PATH = ROOT / "data" / "variants.csv"

# System display metadata (used for cards + badges on the site)
SYSTEM_LABELS = {
    "ABO": "ABO",
    "RHD": "Rh (RHD)",
    "RHCE": "Rh (RHCE)",
    "Duffy": "Duffy (ACKR1)",
    "Kell": "Kell (KEL)",
    "Kidd": "Kidd (SLC14A1)",
    "MNS": "MNS (GYPA/GYPB)",
    "KellOther": "Kell Other (Kpa/Kpb, Jsa/Jsb)",
}

# Fields that vary by source table -> canonical field name.
# Order matters: first match wins.
ALIAS_MAP = {
    "hgvs": ["hgvs_notation", "hgvs_notation_c"],
    "phenotype": ["resulting_abo_phenotype", "resulting_phenotype"],
    "allele_background": [
        "abo_allele_background",
        "rhce_allele_background",
        "ackr1_allele_background",
        "kel_allele_background",
        "gypa_gypb_allele_background",
    ],
    "region": ["genomic_region_element", "genomic_region_element_gene"],
}

PASSTHROUGH_FIELDS = [
    "variant_id", "alternative_notation", "variant_category", "mutation_type",
    "grch38_coordinate", "dbsnp_rs", "reference_allele", "alternate_allele",
    "isbt_allele_designation", "molecular_mechanism", "validation_level",
    "validation_cell_line", "population", "gnomad_v4_af_global",
    "gnomad_v4_af_afr", "gnomad_v4_af_eur", "topmed_af", "be4max_feasibility",
    "abe8e_feasibility", "be_guide_sequence_notes", "bystander_edits",
    "first_report_year", "key_reference", "pubmed_source_url", "audit_status",
    "gnomad_url",
]


def normalize_record(system, meta, record):
    out = {
        "system": system,
        "system_label": SYSTEM_LABELS[system],
        "gene": meta.get("gene"),
        "chromosome": meta.get("chromosome"),
        "strand": meta.get("strand"),
        "isbt_system_code": meta.get("isbt_code"),
    }
    for canonical, sources in ALIAS_MAP.items():
        val = None
        for src in sources:
            if record.get(src):
                val = record[src]
                break
        out[canonical] = val
    for field in PASSTHROUGH_FIELDS:
        out[field] = record.get(field)
    return out


def main():
    raw = json.loads(RAW_PATH.read_text())
    normalized = []
    for system, table in raw.items():
        meta = table["meta"]
        for record in table["variants"]:
            normalized.append(normalize_record(system, meta, record))

    OUT_PATH.write_text(json.dumps(normalized, indent=2))

    # Also emit assets/data.js: a plain <script> global, so the site works
    # when opened directly from disk (file://) with no local server needed
    # to satisfy fetch()'s CORS restrictions on local JSON files.
    js = "// Auto-generated by scripts/normalize_data.py. Do not edit by hand.\n"
    js += "window.VARIANT_DATA = " + json.dumps(normalized, indent=2) + ";\n"
    JS_OUT_PATH.write_text(js)

    # Also emit data/variants.csv for the Downloads page: flat, spreadsheet-friendly.
    if normalized:
        fieldnames = list(normalized[0].keys())
        with CSV_OUT_PATH.open("w", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=fieldnames)
            writer.writeheader()
            writer.writerows(normalized)

    print(f"Wrote {len(normalized)} normalized variant records to {OUT_PATH}, {JS_OUT_PATH}, and {CSV_OUT_PATH}")
    counts = {}
    for r in normalized:
        counts[r["system"]] = counts.get(r["system"], 0) + 1
    for k, v in counts.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
